### ISSUE TITLE
[Bug] Unexpected user profile overflow

### ISSUE THREAD

**Issue by Small-Ku** [SpikeHD/Dorion#118]
**Describe the bug**
When user profile overflow, whole window seems moved upward.

**To Reproduce**
1. Enter any server
2. Find a user that has long user profile by click it with left click

**Expected behavior**
The window should stay. Let user to scroll the user profile would be better.

**Screenshots**
![Screenshot of the bug, with server list blurred](https://github.com/SpikeHD/Dorion/assets/16464896/bc14e6ff-cbfe-4aaa-a66b-5dc54e22b310)

**System Info (please complete the following information):**
 - OS: Windows 11
 - Version: v1.3.0
 - Any other relevant info: 

**Additional context**
This CSS would fix it for now:
```CSS
.layerContainer-2lfOPe {
	overflow: clip;
	top: 30px;
}
.layerContainer-2lfOPe .userProfileOuter-2tQwNf {
	--custom-user-popout-outside-components-height: 30px;
}
```
