### ISSUE TITLE
[Feature Request] Support automatic theme switching between light and dark

### ISSUE THREAD

**Issue by sanyer** [SpikeHD/Dorion#262]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Specify a theme per flavour. One for dark and one for light.

**Describe alternatives you've considered**
Using 

**Additional context**
The simplest way to achieve this - adding an inline [prefers-color-scheme media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), after the `@import` statement, doesn't work for Dorion:
```css
@import url("https://catppuccin.github.io/discord/dist/catppuccin-mocha.theme.css") screen and (prefers-color-scheme: dark);
@import url("https://catppuccin.github.io/discord/dist/catppuccin-latte.theme.css") screen and (prefers-color-scheme: light);
```

However, it does work without the `@import` statements and with explicit code from `*.css_cache.css`:
```css
@media (prefers-color-scheme: light) {
	:root .theme-dark{--brand-experiment: #1e66f5;...
}

@media (prefers-color-scheme: dark) {
	[data-popout-root],html{--brand-experiment: #89b4fa;...
}
```
