### ISSUE TITLE
[Bug] TopNar bar is always using the Native in MacOS

### ISSUE THREAD

**Issue by TerminalFi** [SpikeHD/Dorion#304]
**Describe the bug**

No matter the setting the top narbar always uses the native macos navbar.

**To Reproduce**

Open Dorion

**System Info (please complete the following information):**

```yaml
system_info:
  hardware: MBP 14inch 2022, 10-Core M1 Max, 64 GB, 512GB, Apple M1 Max
  software: macOS 13.3 (22E252)
  kernel_version: Darwin 24.3.0
  open_gl_context_information:
    gl_api_version: 4.1 Metal - 83.1
    glsl_version: 4.10
    vendor: Apple
    renderer: Apple M1 Max
```
